'use client';

import { useState } from 'react';
import { Gauge, ArrowLeft, Loader2, CheckCircle, AlertCircle, Download, Copy } from 'lucide-react';
import Link from 'next/link';
import FileUpload from '@/components/file-upload';
import { downloadJmx, downloadScala } from '@/lib/export-utils';

interface ScriptConfig {
  threads: number;
  rampUp: string;
  duration: string;
}

interface ScriptResult {
  tool: string;
  testType: string;
  fileName: string;
  script: string;
  config: ScriptConfig;
}

const JMETER_SAMPLE = `<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan"
              testname="Bank Indonesia PSP Load Test" enabled="true">
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>

      <hashTree>
        <!-- =================== Thread Group =================== -->
        <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup"
                     testname="PSP Payment API Users" enabled="true">
          <stringProp name="ThreadGroup.num_threads">100</stringProp>
          <stringProp name="ThreadGroup.ramp_time">60</stringProp>
          <stringProp name="ThreadGroup.duration">300</stringProp>
          <boolProp name="ThreadGroup.scheduler">true</boolProp>
          <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>

          <hashTree>
            <!-- HTTP Request Sampler: POST /api/v1/transactions -->
            <HTTPSamplerProxy guiclass="HttpTestSampleGui"
                              testname="POST Create Transaction" enabled="true">
              <stringProp name="HTTPSampler.domain">\${HOST}</stringProp>
              <stringProp name="HTTPSampler.port">\${PORT}</stringProp>
              <stringProp name="HTTPSampler.protocol">https</stringProp>
              <stringProp name="HTTPSampler.path">/api/v1/transactions</stringProp>
              <stringProp name="HTTPSampler.method">POST</stringProp>
              <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
              <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
                <collectionProp name="Arguments.arguments">
                  <elementProp elementType="HTTPArgument">
                    <stringProp name="Argument.value">{
  "amount": \${AMOUNT},
  "currency": "IDR",
  "psp_id": "\${PSP_ID}",
  "reference": "\${REFERENCE_ID}"
}</stringProp>
                  </elementProp>
                </collectionProp>
              </elementProp>
            </HTTPSamplerProxy>

            <!-- Response Assertion -->
            <ResponseAssertion guiclass="AssertionGui" testname="Assert HTTP 200" enabled="true">
              <collectionProp name="Asserion.test_strings">
                <stringProp name="49586">200</stringProp>
              </collectionProp>
              <intProp name="Assertion.test_type">2</intProp>
              <intProp name="Assertion.subject">4</intProp>
            </ResponseAssertion>

            <!-- Constant Timer: 1s think time -->
            <ConstantTimer guiclass="ConstantTimerGui" testname="Think Time" enabled="true">
              <stringProp name="ConstantTimer.delay">1000</stringProp>
            </ConstantTimer>
          </hashTree>
        </ThreadGroup>

        <!-- Listeners -->
        <ResultCollector guiclass="SummaryReport" testname="Summary Report" enabled="true">
          <stringProp name="filename">results/summary.csv</stringProp>
        </ResultCollector>
      </hashTree>
    </TestPlan>
  </hashTree>
</jmeterTestPlan>`;

const GATLING_SAMPLE = `import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

/**
 * Bank Indonesia PSP Performance Test
 * Generated by QAQC4BI MS-APP-003
 * Test Type: Load Test
 */
class PSPLoadSimulation extends Simulation {

  val httpProtocol = http
    .baseUrl("https://psp-api.bi.go.id")
    .acceptHeader("application/json")
    .contentTypeHeader("application/json")
    .header("Authorization", "Bearer \${token}")

  // ── Scenarios ────────────────────────────────────────────────

  val createTransaction = scenario("Create Transaction")
    .feed(csv("data/transactions.csv").circular)
    .exec(
      http("POST /api/v1/transactions")
        .post("/api/v1/transactions")
        .body(StringBody("""
          {
            "amount": \${amount},
            "currency": "IDR",
            "psp_id": "\${psp_id}",
            "reference": "\${reference_id}"
          }
        """)).asJson
        .check(status.is(200))
        .check(jsonPath("$.transaction_id").exists)
        .check(responseTimeInMillis.lte(2000))
    )
    .pause(1)

  val getTransactionStatus = scenario("Get Transaction Status")
    .feed(csv("data/transaction_ids.csv").circular)
    .exec(
      http("GET /api/v1/transactions/:id")
        .get("/api/v1/transactions/\${transaction_id}")
        .check(status.is(200))
        .check(responseTimeInMillis.lte(500))
    )
    .pause(500.milliseconds)

  // ── Load Profile ─────────────────────────────────────────────

  setUp(
    createTransaction.inject(
      rampUsers(50).during(30.seconds),
      constantUsersPerSec(20).during(5.minutes),
      rampUsersPerSec(20).to(0).during(30.seconds)
    ),
    getTransactionStatus.inject(
      rampUsers(50).during(30.seconds),
      constantUsersPerSec(30).during(5.minutes),
      rampUsersPerSec(30).to(0).during(30.seconds)
    )
  ).protocols(httpProtocol)
   .assertions(
     global.responseTime.percentile3.lte(2000),
     global.successfulRequests.percent.gte(99.0),
     global.requestsPerSec.gte(50.0)
   )
}`;

export default function PerfScriptsPage() {
  const [fileContent, setFileContent] = useState('');
  const [fileName, setFileName] = useState('');
  const [tool, setTool] = useState('JMeter');
  const [testType, setTestType] = useState('Load');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ScriptResult | null>(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!fileContent) {
      setError('Please upload an OpenAPI/Swagger specification file.');
      return;
    }
    setError('');
    setLoading(true);
    setResult(null);

    try {
      const res = await fetch('/api/perf-scripts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          spec_content: fileContent,
          spec_name: fileName,
          tool,
          test_type: testType,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `API error: ${res.status}`);
      setResult(data as ScriptResult);
    } catch (err) {
      setError('Failed: ' + (err instanceof Error ? err.message : 'Unknown error'));
      void err;
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    if (!result) return;
    await navigator.clipboard.writeText(result.script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!result) return;
    const baseName = `perf-test-${result.testType.toLowerCase()}`;
    if (result.tool === 'JMeter') {
      downloadJmx(result.script, baseName);
    } else {
      downloadScala(result.script, baseName);
    }
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div>
        <Link
          href="/application"
          className="inline-flex items-center gap-1 text-xs text-[#0f62fe] hover:underline mb-3"
        >
          <ArrowLeft size={12} /> Application QA/QC
        </Link>
        <div className="flex items-start justify-between">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 flex items-center justify-center bg-[#edf5ff] text-[#0f62fe] mt-0.5">
              <Gauge size={20} />
            </div>
            <div>
              <div className="text-[10px] text-[#6f6f6f] font-medium uppercase tracking-wider mb-0.5">
                MS-APP-003
              </div>
              <h1 className="text-xl font-light text-[#161616]">Performance Test Script Generator</h1>
              <p className="text-sm text-[#525252] mt-0.5">
                Upload an OpenAPI/Swagger spec to generate production-ready JMeter or Gatling
                performance test scripts.
              </p>
            </div>
          </div>
          <span className="flex items-center gap-1.5 px-2 py-1 bg-[#defbe6] text-[#198038] text-xs rounded">
            <span className="w-1.5 h-1.5 rounded-full bg-[#198038]" /> Healthy
          </span>
        </div>
      </div>

      {/* Input Panel */}
      <div className="bg-white border border-[#e0e0e0] p-5 space-y-4">
        <h2 className="text-sm font-medium text-[#161616]">Configuration</h2>

        <FileUpload
          label="Upload OpenAPI / Swagger Specification"
          accept=".yaml,.yml,.json"
          description="Supports OpenAPI 3.x and Swagger 2.0 — .yaml, .yml, .json"
          onFileContent={(content, name) => {
            setFileContent(content);
            setFileName(name);
          }}
        />

        {/* Document Preview - show extracted content so user can verify */}
        {fileContent && (
          <div className="space-y-1">
            <div className="flex items-center justify-between">
              <label className="block text-xs font-medium text-[#525252]">
                Extracted Content Preview
                <span className="ml-1 text-[#6f6f6f] font-normal">({fileContent.length.toLocaleString()} characters extracted from {fileName})</span>
              </label>
              <button
                onClick={() => { setFileContent(''); setFileName(''); }}
                className="text-xs text-[#da1e28] hover:underline"
              >
                Clear
              </button>
            </div>
            <div className="bg-[#f4f4f4] border border-[#e0e0e0] p-3 max-h-40 overflow-y-auto text-xs text-[#525252] font-mono whitespace-pre-wrap">
              {fileContent.substring(0, 2000)}{fileContent.length > 2000 ? '\n\n... (truncated for preview)' : ''}
            </div>
          </div>
        )}

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-medium text-[#525252] mb-1">
              Performance Tool
            </label>
            <select
              className="ibm-select"
              value={tool}
              onChange={(e) => setTool(e.target.value)}
            >
              <option value="JMeter">Apache JMeter (.jmx)</option>
              <option value="Gatling">Gatling (.scala)</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-[#525252] mb-1">
              Test Type
            </label>
            <select
              className="ibm-select"
              value={testType}
              onChange={(e) => setTestType(e.target.value)}
            >
              <option value="Load">Load Test — Normal expected traffic</option>
              <option value="Stress">Stress Test — Beyond peak capacity</option>
              <option value="Soak">Soak Test — Extended duration stability</option>
              <option value="Spike">Spike Test — Sudden traffic burst</option>
            </select>
          </div>
        </div>

        {error && (
          <div className="ibm-notification ibm-notification-error flex items-center gap-2">
            <AlertCircle size={16} className="text-[#da1e28] flex-shrink-0" />
            <span className="text-sm text-[#da1e28]">{error}</span>
          </div>
        )}

        <div className="flex items-center gap-3">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="btn-primary flex items-center gap-2 disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                Generating Script...
              </>
            ) : (
              <>
                <Gauge size={16} />
                Generate Performance Script
              </>
            )}
          </button>
          {result && (
            <span className="flex items-center gap-1.5 text-xs text-[#198038]">
              <CheckCircle size={14} />
              {result.tool} {result.testType} script ready
            </span>
          )}
        </div>
      </div>

      {/* Results */}
      {result && (
        <div className="space-y-4">
          {/* Config Summary */}
          <div className="grid grid-cols-4 gap-3">
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Tool</div>
              <div className="text-lg font-medium text-[#0f62fe]">{result.tool}</div>
              <div className="text-xs text-[#6f6f6f]">Test framework</div>
            </div>
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Virtual Users</div>
              <div className="text-2xl font-light text-[#161616]">{result.config.threads}</div>
              <div className="text-xs text-[#6f6f6f]">Concurrent threads</div>
            </div>
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Ramp-up</div>
              <div className="text-2xl font-light text-[#161616]">{result.config.rampUp}</div>
              <div className="text-xs text-[#6f6f6f]">Time to peak load</div>
            </div>
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Duration</div>
              <div className="text-2xl font-light text-[#161616]">{result.config.duration}</div>
              <div className="text-xs text-[#6f6f6f]">Total test run time</div>
            </div>
          </div>

          {/* Script Code Block */}
          <div className="bg-white border border-[#e0e0e0]">
            <div className="flex items-center justify-between px-4 py-3 border-b border-[#e0e0e0]">
              <div>
                <h3 className="text-sm font-medium text-[#161616]">
                  Generated Script — {result.tool} ({result.testType} Test)
                </h3>
                <p className="text-xs text-[#525252] mt-0.5">
                  {result.fileName}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="btn-ghost flex items-center gap-1.5 !min-h-[32px] !py-1 !px-3 text-xs"
                >
                  <Copy size={14} />
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="btn-primary flex items-center gap-1.5 !min-h-[36px] !py-1 !px-4 !text-sm"
                >
                  <Download size={14} />
                  {result.tool === 'JMeter' ? 'Download .jmx' : 'Download .scala'}
                </button>
              </div>
            </div>
            <div className="overflow-auto" style={{ maxHeight: '520px' }}>
              <pre
                className="p-5 text-xs leading-relaxed font-mono overflow-x-auto"
                style={{
                  backgroundColor: '#161616',
                  color: '#f4f4f4',
                  minHeight: '200px',
                }}
              >
                <code>{result.script}</code>
              </pre>
            </div>
          </div>

          <div className="ibm-notification ibm-notification-info text-xs text-[#525252]">
            Script generated with{' '}
            <strong className="text-[#161616]">{result.config.threads} virtual users</strong>, {result.config.rampUp} ramp-up, and{' '}
            <strong className="text-[#161616]">{result.config.duration}</strong> test duration. Review thresholds before executing against production.
          </div>
        </div>
      )}
    </div>
  );
}
