'use client';

import { useState } from 'react';
import { Code2, ArrowLeft, Loader2, CheckCircle, AlertCircle, Download, Copy, FileCode } from 'lucide-react';
import Link from 'next/link';
import { downloadPython, downloadTextFile } from '@/lib/export-utils';

interface GeneratedFile {
  name: string;
  content: string;
}

interface CodeGenResult {
  framework: string;
  pattern: string;
  files: GeneratedFile[];
  summary: {
    totalFiles: number;
    totalTests: number;
    pattern: string;
    coverage: string;
  };
}

const SELENIUM_PAGE_OBJECT = `# Generated by QAQC4BI MS-APP-004
# Framework: Selenium + Python (Page Object Model)

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class PaymentPage:
    """Page Object for the Payment Gateway page."""

    # ── Locators ────────────────────────────────────────────────
    CARD_NUMBER_INPUT    = (By.ID, "card-number")
    EXPIRY_INPUT         = (By.ID, "card-expiry")
    CVV_INPUT            = (By.ID, "card-cvv")
    CARDHOLDER_INPUT     = (By.ID, "cardholder-name")
    PAY_BUTTON           = (By.XPATH, "//button[@data-testid='pay-now-btn']")
    SUCCESS_BANNER       = (By.CSS_SELECTOR, ".payment-success-banner")
    ERROR_MESSAGE        = (By.CSS_SELECTOR, ".payment-error-message")
    TRANSACTION_ID_LABEL = (By.ID, "transaction-id")

    def __init__(self, driver):
        self.driver = driver
        self.wait   = WebDriverWait(driver, timeout=15)

    def navigate(self, base_url: str):
        self.driver.get(f"{base_url}/payment")
        self.wait.until(EC.presence_of_element_located(self.PAY_BUTTON))

    def enter_card_details(self, card_number: str, expiry: str, cvv: str, name: str):
        self._fill(self.CARD_NUMBER_INPUT, card_number)
        self._fill(self.EXPIRY_INPUT, expiry)
        self._fill(self.CVV_INPUT, cvv)
        self._fill(self.CARDHOLDER_INPUT, name)

    def click_pay(self):
        self.wait.until(EC.element_to_be_clickable(self.PAY_BUTTON)).click()

    def is_success_displayed(self) -> bool:
        try:
            self.wait.until(EC.visibility_of_element_located(self.SUCCESS_BANNER))
            return True
        except Exception:
            return False

    def get_error_message(self) -> str:
        el = self.wait.until(EC.visibility_of_element_located(self.ERROR_MESSAGE))
        return el.text.strip()

    def get_transaction_id(self) -> str:
        el = self.wait.until(EC.visibility_of_element_located(self.TRANSACTION_ID_LABEL))
        return el.text.strip()

    # ── Helpers ─────────────────────────────────────────────────
    def _fill(self, locator, value: str):
        element = self.wait.until(EC.element_to_be_clickable(locator))
        element.clear()
        element.send_keys(value)`;

const SELENIUM_TEST_CLASS = `# Generated by QAQC4BI MS-APP-004
# Framework: Selenium + Python + pytest

import pytest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from pages.payment_page import PaymentPage


BASE_URL = "https://psp-staging.bi.go.id"


@pytest.fixture(scope="function")
def driver():
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    drv = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()), options=options
    )
    drv.set_window_size(1366, 768)
    yield drv
    drv.quit()


@pytest.fixture
def payment_page(driver):
    page = PaymentPage(driver)
    page.navigate(BASE_URL)
    return page


# ── Test Cases ───────────────────────────────────────────────────

class TestPaymentGateway:

    def test_successful_payment_with_valid_card(self, payment_page):
        """TC-001: Positive — Valid card details should result in successful payment."""
        payment_page.enter_card_details(
            card_number="4111 1111 1111 1111",
            expiry="12/28",
            cvv="123",
            name="JOHN DOE",
        )
        payment_page.click_pay()

        assert payment_page.is_success_displayed(), "Success banner should be visible"
        txn_id = payment_page.get_transaction_id()
        assert txn_id.startswith("TXN-"), f"Expected TXN-XXXXXXX, got {txn_id}"

    def test_payment_fails_with_expired_card(self, payment_page):
        """TC-002: Negative — Expired card should display error message."""
        payment_page.enter_card_details(
            card_number="4111 1111 1111 1111",
            expiry="01/20",
            cvv="123",
            name="JOHN DOE",
        )
        payment_page.click_pay()

        error = payment_page.get_error_message()
        assert "expired" in error.lower(), f"Expected expiry error, got: {error}"

    def test_payment_fails_with_invalid_cvv(self, payment_page):
        """TC-003: Negative — Invalid CVV should display card error."""
        payment_page.enter_card_details(
            card_number="4111 1111 1111 1111",
            expiry="12/28",
            cvv="00",   # invalid
            name="JOHN DOE",
        )
        payment_page.click_pay()

        error = payment_page.get_error_message()
        assert error, "An error message should be displayed for invalid CVV"

    def test_pay_button_disabled_with_empty_fields(self, payment_page):
        """TC-004: Edge Case — Pay button should be disabled when fields are empty."""
        from selenium.webdriver.common.by import By
        btn = payment_page.driver.find_element(By.XPATH, "//button[@data-testid='pay-now-btn']")
        assert not btn.is_enabled(), "Pay button should be disabled without card details"`;

const KATALON_SAMPLE = `import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

/**
 * Test Suite: Payment Gateway
 * Generated by QAQC4BI MS-APP-004 (Katalon Studio)
 */

// ── Test Case: TC-001 Successful Payment ────────────────────────
WebUI.openBrowser('')
WebUI.navigateToUrl('https://psp-staging.bi.go.id/payment')

// Step 1: Enter card number
WebUI.setText(findTestObject('Payment/txt_CardNumber'), '4111 1111 1111 1111')

// Step 2: Enter expiry
WebUI.setText(findTestObject('Payment/txt_Expiry'), '12/28')

// Step 3: Enter CVV
WebUI.setText(findTestObject('Payment/txt_CVV'), '123')

// Step 4: Enter cardholder name
WebUI.setText(findTestObject('Payment/txt_CardholderName'), 'JOHN DOE')

// Step 5: Click Pay Now
WebUI.click(findTestObject('Payment/btn_PayNow'))

// Step 6: Verify success banner
WebUI.waitForElementVisible(findTestObject('Payment/banner_Success'), 15)
WebUI.verifyElementVisible(findTestObject('Payment/banner_Success'))

// Step 7: Verify transaction ID
String txnId = WebUI.getText(findTestObject('Payment/lbl_TransactionId'))
assert txnId.startsWith('TXN-') : "Transaction ID format invalid: \${txnId}"

WebUI.closeBrowser()`;


export default function AutomationCodegenPage() {
  const [steps, setSteps] = useState('');
  const [framework, setFramework] = useState('Selenium + Python');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CodeGenResult | null>(null);
  const [error, setError] = useState('');
  const [activeFile, setActiveFile] = useState(0);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  const handleGenerate = async () => {
    if (!steps.trim()) {
      setError('Please enter manual test steps to generate automation code.');
      return;
    }
    setError('');
    setLoading(true);
    setResult(null);

    try {
      const res = await fetch('/api/automation-codegen', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ test_steps: steps, framework }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `API error: ${res.status}`);
      setResult(data as CodeGenResult);
      setActiveFile(0);
    } catch (err) {
      setError('Failed: ' + (err instanceof Error ? err.message : 'Unknown error'));
      void err;
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async (idx: number) => {
    if (!result) return;
    await navigator.clipboard.writeText(result.files[idx].content);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const handleDownloadFile = (file: GeneratedFile) => {
    const safeName = file.name.replace(/\//g, '_');
    if (safeName.endsWith('.py')) {
      downloadPython(file.content, safeName);
    } else if (safeName.endsWith('.groovy')) {
      downloadTextFile(file.content, safeName, 'text/x-groovy');
    } else {
      downloadTextFile(file.content, safeName, 'text/plain');
    }
  };

  const handleDownloadAll = () => {
    if (!result) return;
    result.files.forEach((file) => handleDownloadFile(file));
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div>
        <Link
          href="/application"
          className="inline-flex items-center gap-1 text-xs text-[#0f62fe] hover:underline mb-3"
        >
          <ArrowLeft size={12} /> Application QA/QC
        </Link>
        <div className="flex items-start justify-between">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 flex items-center justify-center bg-[#edf5ff] text-[#0f62fe] mt-0.5">
              <Code2 size={20} />
            </div>
            <div>
              <div className="text-[10px] text-[#6f6f6f] font-medium uppercase tracking-wider mb-0.5">
                MS-APP-004
              </div>
              <h1 className="text-xl font-light text-[#161616]">Automation Test Code Generator</h1>
              <p className="text-sm text-[#525252] mt-0.5">
                Enter manual test steps and select a framework to generate structured automation
                code with page objects and test classes.
              </p>
            </div>
          </div>
          <span className="flex items-center gap-1.5 px-2 py-1 bg-[#defbe6] text-[#198038] text-xs rounded">
            <span className="w-1.5 h-1.5 rounded-full bg-[#198038]" /> Healthy
          </span>
        </div>
      </div>

      {/* Input Panel */}
      <div className="bg-white border border-[#e0e0e0] p-5 space-y-4">
        <h2 className="text-sm font-medium text-[#161616]">Input Test Steps</h2>

        <div>
          <label className="block text-xs font-medium text-[#525252] mb-1">
            Manual Test Steps
          </label>
          <textarea
            className="ibm-textarea"
            rows={8}
            placeholder={`Describe your test steps in plain language, e.g.:
1. Navigate to the payment page
2. Enter card number "4111 1111 1111 1111"
3. Enter expiry date "12/28" and CVV "123"
4. Enter cardholder name "JOHN DOE"
5. Click the "Pay Now" button
6. Verify success banner is displayed
7. Verify transaction ID starts with "TXN-"`}
            value={steps}
            onChange={(e) => setSteps(e.target.value)}
          />
        </div>

        <div className="max-w-sm">
          <label className="block text-xs font-medium text-[#525252] mb-1">
            Automation Framework
          </label>
          <select
            className="ibm-select"
            value={framework}
            onChange={(e) => setFramework(e.target.value)}
          >
            <option value="Selenium + Python">Selenium + Python (Page Object Model)</option>
            <option value="Katalon">Katalon Studio (Keyword-Driven)</option>
          </select>
        </div>

        {error && (
          <div className="ibm-notification ibm-notification-error flex items-center gap-2">
            <AlertCircle size={16} className="text-[#da1e28] flex-shrink-0" />
            <span className="text-sm text-[#da1e28]">{error}</span>
          </div>
        )}

        <div className="flex items-center gap-3">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="btn-primary flex items-center gap-2 disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                Generating Code...
              </>
            ) : (
              <>
                <Code2 size={16} />
                Generate Automation Code
              </>
            )}
          </button>
          {result && (
            <span className="flex items-center gap-1.5 text-xs text-[#198038]">
              <CheckCircle size={14} />
              {result.summary?.totalFiles ?? 0} file{(result.summary?.totalFiles ?? 0) !== 1 ? 's' : ''} generated
            </span>
          )}
        </div>
      </div>

      {/* Results */}
      {result && (
        <div className="space-y-4">
          {/* Summary Cards */}
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Files Generated</div>
              <div className="text-2xl font-light text-[#0f62fe]">{result.summary?.totalFiles ?? 0}</div>
              <div className="text-xs text-[#6f6f6f]">{result.framework}</div>
            </div>
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Test Cases</div>
              <div className="text-2xl font-light text-[#161616]">{result.summary?.totalTests ?? 0}</div>
              <div className="text-xs text-[#6f6f6f]">Automated test methods</div>
            </div>
            <div className="bg-white border border-[#e0e0e0] p-4">
              <div className="text-xs text-[#525252] uppercase tracking-wider mb-1">Pattern Used</div>
              <div className="text-sm font-medium text-[#161616] mt-1">{result.summary?.pattern ?? ''}</div>
              <div className="text-xs text-[#6f6f6f]">Architecture style</div>
            </div>
          </div>

          {/* File tabs + code blocks */}
          <div className="bg-white border border-[#e0e0e0]">
            {/* Tab Bar */}
            <div className="flex items-center gap-0 border-b border-[#e0e0e0] overflow-x-auto">
              {(result.files || []).map((file, idx) => (
                <button
                  key={file.name}
                  onClick={() => setActiveFile(idx)}
                  className={`flex items-center gap-1.5 px-4 py-2.5 text-xs whitespace-nowrap border-b-2 transition-colors ${
                    activeFile === idx
                      ? 'border-[#0f62fe] text-[#0f62fe] bg-[#edf5ff]'
                      : 'border-transparent text-[#525252] hover:bg-[#f4f4f4]'
                  }`}
                >
                  <FileCode size={13} />
                  {file.name}
                </button>
              ))}
              <div className="ml-auto flex items-center gap-2 px-3">
                <button
                  onClick={() => handleCopy(activeFile)}
                  className="btn-ghost flex items-center gap-1.5 !min-h-[30px] !py-1 !px-3 text-xs"
                >
                  <Copy size={13} />
                  {copiedIdx === activeFile ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={() => handleDownloadFile(result.files[activeFile])}
                  className="btn-ghost flex items-center gap-1.5 !min-h-[30px] !py-1 !px-3 text-xs"
                >
                  <Download size={13} />
                  Download
                </button>
                <button
                  onClick={handleDownloadAll}
                  className="btn-primary flex items-center gap-1.5 !min-h-[30px] !py-1 !px-3 text-xs"
                >
                  <Download size={13} />
                  Download All
                </button>
              </div>
            </div>

            {/* Active file info */}
            <div className="px-4 py-2 bg-[#f4f4f4] border-b border-[#e0e0e0] flex items-center gap-2">
              <FileCode size={13} className="text-[#6f6f6f]" />
              <span className="text-xs text-[#525252]">{result.files[activeFile].name}</span>
            </div>

            {/* Code Block */}
            <div className="overflow-auto" style={{ maxHeight: '520px' }}>
              <pre
                className="p-5 text-xs leading-relaxed font-mono overflow-x-auto"
                style={{ backgroundColor: '#161616', color: '#f4f4f4', minHeight: '200px' }}
              >
                <code>{result.files[activeFile].content}</code>
              </pre>
            </div>
          </div>

          {/* Info notification */}
          <div className="ibm-notification ibm-notification-info text-xs text-[#525252]">
            Generated <strong className="text-[#161616]">{result.summary?.totalFiles ?? 0} file{(result.summary?.totalFiles ?? 0) !== 1 ? 's' : ''}</strong> using{' '}
            <strong className="text-[#161616]">{result.framework}</strong> with the{' '}
            <strong className="text-[#161616]">{result.summary?.pattern ?? ''}</strong> architecture.{' '}
            {result.summary?.totalTests ?? 0} test method{(result.summary?.totalTests ?? 0) !== 1 ? 's' : ''} ready for execution.
            {result.summary.coverage ? ` Coverage: ${result.summary.coverage}.` : ''}
          </div>
        </div>
      )}
    </div>
  );
}
